# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               ComBio
tagline:             '走南闯北的骏马——马博士博客'
description:         '一个对科研有想法的博士。领域：园艺学、设施园艺工程、丛枝菌根真菌（AMF）、生物信息学'
url:                 http://combio.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              CodingFish
  email:             codingfish@yeah.net

# Custom vars
version:             1.0.0
